


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ayubs
 */
import java.io.*;
import jxl.*;
import java.awt.*;

public class StartPage extends javax.swing.JFrame {

    
    /**
     * Creates new form StartPage
     */
    List allElements;
    
    public StartPage() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(900,500);
        reviewButton.setOpaque(false);
        reviewButton.setContentAreaFilled(false); //to make the content area transparent
        
        quizMeButton.setOpaque(false);
        quizMeButton.setContentAreaFilled(false); //to make the content area transparent
        
        crosswordButton.setOpaque(false);
        crosswordButton.setContentAreaFilled(false); //to make the content area transparent
        
        exitButton.setOpaque(false);
        exitButton.setContentAreaFilled(false); //to make the content area transparent
        //reviewButton.setBorderPainted(false); //to make the borders transparent
       

        //ystem.out.println(this.size());
        try{
        readFile();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    String name;
    String symbol;
    int num;
    double weight;
    double melting;
    double boiling;
    
    private void readFile()throws Exception{
        allElements = new List();
        File f = new File("C:\\Users\\ayubs\\OneDrive\\Desktop\\Ayub\\Projects\\Java\\PeriodicTable\\src\\completeData.xls");
        Workbook wb = Workbook.getWorkbook(f);
        Sheet s = wb.getSheet(0);
        int rows = s.getRows();
        int cols = s.getColumns();
        for(int i = 0; i< rows; i++){
            for(int j = 0; j< 6; j++){
                Cell c = s.getCell(j,i);
                if(i != 0){
                    switch (j){
                    case 0:
                        name = c.getContents();
                        break;
                    case 1:
                        symbol = c.getContents();
                        break;
                    case 2:
                        num = Integer.parseInt(c.getContents());
                        break;
                    case 3:
                        try{
                            weight = Double.parseDouble(c.getContents());
                        }catch(Exception e){
                            weight = 0.0;
                        }
                    case 4:
                        try{
                            melting = Double.parseDouble(c.getContents());
                        }catch(Exception e){
                            melting = 0.0;
                        }
                        break;
                    case 5:
                        try{
                            boiling = Double.parseDouble(c.getContents());
                        }catch(Exception e){
                            boiling = 0.0;
                        }
                        break;
                    default:
                    }
                }
            }
            if(i!=0){
                allElements.addElement(new Element(name, symbol, num, weight, melting, boiling));
            }
        }
        System.out.println("list is initialized");
        //allElements.displayListForward();
        //allElements.displayListBackward();
    }
    
    public boolean containsNum(String temp){
        boolean contains = false;
        char [] chars = temp.toCharArray();
        for(int i = 0; i< chars.length; i++){
            if(Character.isDigit(chars[i])){
                contains = true;
            }
        }
        return contains;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        quizMeButton = new javax.swing.JButton();
        crosswordButton = new javax.swing.JButton();
        reviewButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(110, 110));
        setLocationByPlatform(true);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here you can review all the elements this universe has to offer as well as Quiz your understanding of them!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 680, 80));

        quizMeButton.setBackground(new java.awt.Color(153, 153, 153));
        quizMeButton.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        quizMeButton.setForeground(new java.awt.Color(255, 255, 255));
        quizMeButton.setText("Quiz Me");
        quizMeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quizMeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        quizMeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeQuizEnterColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonChangeColor(evt);
            }
        });
        quizMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizMeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quizMeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 110, 40));

        crosswordButton.setBackground(new java.awt.Color(153, 153, 153));
        crosswordButton.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        crosswordButton.setForeground(new java.awt.Color(255, 255, 255));
        crosswordButton.setText("Crossword");
        crosswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crosswordButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        crosswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                speedEnteredChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonChangeColor(evt);
            }
        });
        crosswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crosswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(crosswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 130, 40));

        reviewButton.setBackground(new java.awt.Color(153, 153, 153));
        reviewButton.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        reviewButton.setForeground(new java.awt.Color(255, 255, 255));
        reviewButton.setText("Review");
        reviewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reviewButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        reviewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonChangeColor(evt);
            }
        });
        reviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reviewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, 40));
        reviewButton.getAccessibleContext().setAccessibleDescription("");

        exitButton.setBackground(new java.awt.Color(153, 153, 153));
        exitButton.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeExitColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonChangeColor(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 70, 40));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Periodic Table Made Easy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 640, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundImage.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ReviewPage rpg = new ReviewPage(allElements);
        rpg.setVisible(true);
    }//GEN-LAST:event_reviewButtonActionPerformed

    private void quizMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizMeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QuizPage qp = new QuizPage(allElements);
        qp.setVisible(true);
    }//GEN-LAST:event_quizMeButtonActionPerformed

    private void changeColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeColor
        // TODO add your handling code here:
        reviewButton.setForeground(Color.GRAY);
    }//GEN-LAST:event_changeColor

    
    private void changeQuizEnterColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeQuizEnterColor
        // TODO add your handling code here:
        quizMeButton.setForeground(Color.GRAY);
    }//GEN-LAST:event_changeQuizEnterColor

    private void speedEnteredChangeColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speedEnteredChangeColor
        // TODO add your handling code here:
        crosswordButton.setForeground(Color.GRAY);
    }//GEN-LAST:event_speedEnteredChangeColor

    private void exitButtonChangeColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonChangeColor
        reviewButton.setForeground(Color.WHITE);
        quizMeButton.setForeground(Color.WHITE);
        crosswordButton.setForeground(Color.WHITE);
        exitButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitButtonChangeColor

    private void changeExitColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeExitColor
        // TODO add your handling code here:
        exitButton.setForeground(Color.GRAY);
    }//GEN-LAST:event_changeExitColor

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void crosswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crosswordButtonActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        crosswordPage cwp = new crosswordPage(allElements);
        cwp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crosswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crosswordButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton quizMeButton;
    private javax.swing.JButton reviewButton;
    // End of variables declaration//GEN-END:variables
}
